stages:
  - build
variables:
  GIT_SUBMODULE_STRATEGY: recursive
dev:
  stage: build
  image: docker:19
  only:
    - dev
  tags:
    - docker
  script:
    - docker build --build-arg VITE_BUILD_MODE=dev -t reg.paradise-soft.com.tw:5000/morse-web:dev .
    - docker push reg.paradise-soft.com.tw:5000/morse-web:dev

uat:
  stage: build
  image: docker:19
  only:
    - uat
  tags:
    - docker
  script:
    - docker build --build-arg VITE_BUILD_MODE=uat -t reg.paradise-soft.com.tw:5000/morse-web:uat .
    - docker push reg.paradise-soft.com.tw:5000/morse-web:uat

tags:
  stage: build
  image: docker:19
  only:
    - tags
  tags:
    - docker
  script:
    - docker build --build-arg VITE_BUILD_MODE=prod -t reg.paradise-soft.com.tw:5000/morse-web:$CI_COMMIT_TAG . 
    - docker push reg.paradise-soft.com.tw:5000/morse-web:$CI_COMMIT_TAG

